[package]
name = "party-hat-bluepill"
version = "0.1.0"
authors = ["Aubrey Powell"]
edition = "2018"

[dependencies]
cortex-m = "0.5.6"
cortex-m-rt = "0.6.3"
panic-itm = "0.4.0"
nb = "0.1.2"

[dependencies.stm32f1xx-hal]
version = "0.2.0"
features = ["stm32f103", "rt"]
